### ISSUE TITLE
Lack of documentation/examples

### ISSUE THREAD

**Issue by rmoehn** [gehring/tilecoding#2]
I find the API hard to understand. It's not clear what shapes of arrays are expected and in which axes some of the arguments have to be arranged. Also, strange behaviours occur when one uses `int`s instead of `float`s as parameters. As minimum documentation, examples would be nice. Here's a first example:

``` python
tc = representation.TileCoding(input_indices=[[0]],
                               ntiles=[5],
                               ntilings=[2],
                               state_range=np.array([[0.], [20.]]),
                               hashing=None,
                               bias_term=False)

for x in xrange(-6, 31):
    t1_marker = "1>" if 0 <= x <= 20 and x % 5 == 0 else "  "
    t2_marker = "2>" if 0 <= x <= 23 and (x+2) % 5 == 0 else "  "
    print t1_marker, t2_marker, "%2d" % x, tc(np.array([float(x)]))
```

Prints:

```
      -6 [0 5]
      -5 [0 5]
      -4 [0 5]
      -3 [0 5]
      -2 [0 5]
      -1 [0 5]
1>     0 [1 5]
       1 [1 5]
       2 [1 5]
   2>  3 [1 6]
       4 [1 6]
1>     5 [2 6]
       6 [2 6]
       7 [2 6]
   2>  8 [2 7]
       9 [2 7]
1>    10 [3 7]
      11 [3 7]
      12 [3 7]
   2> 13 [3 8]
      14 [3 8]
1>    15 [4 8]
      16 [4 8]
      17 [4 8]
   2> 18 [4 9]
      19 [4 9]
1>    20 [4 9]
      21 [4 9]
      22 [4 9]
   2> 23 [4 9]
      24 [4 9]
      25 [4 9]
      26 [4 9]
      27 [4 9]
      28 [4 9]
      29 [4 9]
      30 [4 9]
```

I might make up more examples as I try to understand the API. Not sure where to put them, though. – I don't want to blow up the code. Maybe the wiki?

**Comment by gehring** [comment]
I will look into adding some documentation and use cases to the readme. I should have time to deal with this in a day or two. Can you elaborate on where you get inconsistent behaviour when using floats/ints?

**Comment by rmoehn** [comment]
Sounds good.

Inconsistent behaviour when using ints:

``` python
tc = representation.TileCoding(input_indices=[[0]],
                               ntiles=[5],
                               ntilings=[2],
                               state_range=np.array([[0.], [10.]]),
                               hashing=None,
                               bias_term=False)

int_tc = representation.TileCoding(input_indices=[[0]],
                                   ntiles=[5],
                                   ntilings=[2],
                                   state_range=np.array([[0], [10]]), # int bounds
                                   hashing=None,
                                   bias_term=False)

for x in xrange(-3, 15):
    print "%2d" % x, tc(np.array([float(x)])), tc(np.array([x])), \
                     int_tc(np.array([float(x)])), int_tc(np.array([x]))
```

Prints:

```
#  float bounds  int bounds
#  float int     float int
-3 [0 5] [0 5]   [0 5] [0 5] ← int inputs don't work at all.
-2 [0 5] [0 5]   [0 5] [0 5]
-1 [0 5] [0 5]   [0 5] [0 5]
 0 [1 5] [1 5]   [0 5] [0 5] ← From here the results for float input are different.
 1 [1 5] [1 5]   [1 5] [0 5]
 2 [1 6] [1 6]   [1 6] [0 5]
 3 [2 6] [2 6]   [2 6] [0 5]
 4 [2 7] [2 7]   [2 7] [0 5]
 5 [3 7] [3 7]   [2 7] [0 5]
 6 [3 7] [3 7]   [3 7] [0 5]
 7 [3 8] [3 8]   [3 8] [0 5]
 8 [4 8] [4 8]   [4 8] [0 5] ← Until here.
 9 [4 9] [4 9]   [4 9] [0 5]
10 [4 9] [4 9]   [4 9] [4 9]
11 [4 9] [4 9]   [4 9] [4 9]
12 [4 9] [4 9]   [4 9] [4 9]
13 [4 9] [4 9]   [4 9] [4 9]
14 [4 9] [4 9]   [4 9] [4 9]
   ↑     ↑
 These are all the same, i. e., int input is fine.
```

Usually it's not wise to mix ints and floats anyway, but a hint in the documentation would be nice for those who forget (like me).

I also wonder why the indices start at 1, but I guess the `IndexTo…` projections fix that somehow.

**Comment by gehring** [comment]
The inconsistent behaviour with int vs float state range has been fixed (with a float cast of the state range). 

Things are indexed by zero but the way the state is normalized between 0.0 and 1.0 is conservative in order to make sure there is no lose of resolution at the boundaries regardless of the offsets given (i.e., there will always be ntilings overlapping at that spot, with each tile of the same size). The issue only affects tilings with offset 0. I'm not sure what would be an elegant way to insure no lose of resolution for all offsets as well as avoid this (minor) issue or if it is even worth solving.

I'll add a few examples tomorrow.

**Comment by rmoehn** [comment]
Thanks!

I wonder why I even asked about the indices starting at 1. I'd implemented a primitive tilecoder myself and made the same decision. Also, I'm using random offsets and most likely none of them is 0. So I'd say this isn't an issue. Sorry for bringing up a non-issue.

**Comment by gehring** [comment]
I've added some usage call for the constructor of TileCoding. There is still missing examples for hashing the indices and using the tilecoding for linear function approximation (either with explicit vectors or with indices).

Please let me know if things are clear and the format is useful.

**Comment by rmoehn** [comment]
Wow, it looks quite comprehensive! I will read it through more carefully tomorrow.

**Comment by rmoehn** [comment]
Now I also understand why it can do multiple sets of tilings. Thanks a lot for your efforts!
